version: '3'

services:
  project_db:
    container_name: "project_db"
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    networks:
      - db_network
    volumes:
      - pgdata_volume:/var/lib/postgresql/data/
      - ./postgres/dump:/dump
      - ./postgres/init:/docker-entrypoint-initdb.d

  project_app:
    container_name: "project_app"
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        PGPASSWORD: $POSTGRES_PASSWORD
    tty: true
    expose:
      - 8000
    ports:
      - "8001:8000"
    restart: always
    networks:
      - db_network
    volumes:
      - ./app:/code
    depends_on:
      - project_db

networks:
  db_network:
    driver: bridge

volumes:
  pgdata_volume:
